/**
 * Database connection pool and query helpers.
 * Uses pg (node-postgres) with connection pooling suitable for Lambda.
 *
 * In AWS, the DB password is retrieved from Secrets Manager (generated by CDK).
 * Locally, it uses the DB_PASSWORD environment variable directly.
 */

import { Pool, PoolClient, QueryResult, QueryResultRow } from 'pg';
import { SecretsManagerClient, GetSecretValueCommand } from '@aws-sdk/client-secrets-manager';

let pool: Pool | null = null;
let cachedPassword: string | null = null;

/**
 * Retrieve the database password from Secrets Manager or env var.
 */
async function getDbPassword(): Promise<string> {
  // If password is directly provided (local dev), use it
  if (process.env.DB_PASSWORD) {
    return process.env.DB_PASSWORD;
  }

  // Return cached password if available (avoids repeated API calls in Lambda)
  if (cachedPassword) return cachedPassword;

  // Fetch from Secrets Manager
  const secretArn = process.env.DB_SECRET_ARN;
  if (!secretArn) {
    throw new Error('Neither DB_PASSWORD nor DB_SECRET_ARN is set');
  }

  const client = new SecretsManagerClient({});
  const command = new GetSecretValueCommand({ SecretId: secretArn });
  const response = await command;
  const result = await client.send(command);

  if (!result.SecretString) {
    throw new Error('Secret value is empty');
  }

  const secret = JSON.parse(result.SecretString);
  cachedPassword = secret.password;
  return cachedPassword!;
}

/**
 * Get or create the database connection pool.
 * In Lambda, the pool persists across warm invocations.
 */
export async function getPool(): Promise<Pool> {
  if (!pool) {
    const password = await getDbPassword();
    pool = new Pool({
      host: process.env.DB_HOST,
      port: parseInt(process.env.DB_PORT || '5432', 10),
      database: process.env.DB_NAME,
      user: process.env.DB_USER,
      password,
      ssl: process.env.DB_SSL === 'true' ? { rejectUnauthorized: false } : undefined,
      max: 5,
      idleTimeoutMillis: 60000,
      connectionTimeoutMillis: 5000,
    });
  }
  return pool;
}

/**
 * Execute a parameterized query.
 */
export async function query<T extends QueryResultRow = Record<string, unknown>>(
  text: string,
  params?: unknown[]
): Promise<QueryResult<T>> {
  const p = await getPool();
  return p.query<T>(text, params);
}

/**
 * Execute a query and return the first row, or null if no results.
 */
export async function queryOne<T extends QueryResultRow = Record<string, unknown>>(
  text: string,
  params?: unknown[]
): Promise<T | null> {
  const result = await query<T>(text, params);
  return result.rows[0] ?? null;
}

/**
 * Execute a query and return all rows.
 */
export async function queryMany<T extends QueryResultRow = Record<string, unknown>>(
  text: string,
  params?: unknown[]
): Promise<T[]> {
  const result = await query<T>(text, params);
  return result.rows;
}

/**
 * Run a callback within a database transaction.
 * Automatically commits on success, rolls back on error.
 */
export async function withTransaction<T>(
  callback: (client: PoolClient) => Promise<T>
): Promise<T> {
  const p = await getPool();
  const client = await p.connect();
  try {
    await client.query('BEGIN');
    const result = await callback(client);
    await client.query('COMMIT');
    return result;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}
